school/classroom/urls.py
from django.urls import path
from .views import HomeView, ThankYouView, ContactFormView, TeacherCreateView, TeacherListView, TeacherDetailView, TeacherUpdateView, TeacherDeleteView

app_name = 'classroom'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('thank_you/', ThankYouView.as_view(), name='thank_you'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('create_teacher/', TeacherCreateView.as_view(), name='create_teacher'),
    path('list_teacher/', TeacherListView.as_view(), name='teacher_list'),
    path('teacher_detail/<int:pk>/', TeacherDetailView.as_view(), name='teacher_detail'),
    path('teacher_update/<int:pk>/', TeacherUpdateView.as_view(), name='teacher_update'),
    path('teacher_delete/<int:pk>/', TeacherDeleteView.as_view(), name='teacher_delete'),
]

school/school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("classroom/", include("classroom.urls")),
]

school/classroom/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    subject = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.first_name} {self.last_name} teaches {self.subject}"

school/classroom/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)
    

school/classroom/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView, CreateView, ListView, DetailView, UpdateView, DeleteView
from classroom.forms import ContactForm
from django.urls import reverse_lazy
from classroom.models import Teacher

# Create your views here.
def home_view(request):
    return render(request, 'classroom/home.html', {})

class HomeView(TemplateView):
    template_name = 'classroom/home.html'

class ThankYouView(TemplateView):
    template_name = 'classroom/thank_you.html'

class TeacherCreateView(CreateView):
    template_name = 'classroom/teacher_form.html'
    model = Teacher
    fields = '__all__'
    success_url = reverse_lazy('classroom:thank_you')

class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'classroom/contact.html'
    success_url = reverse_lazy('classroom:thank_you')
    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

class TeacherListView(ListView):
    model = Teacher
    queryset = Teacher.objects.order_by('first_name')
    template_name = 'classroom/teacher_list.html'
    context_object_name = 'teachers'

class TeacherDetailView(DetailView):
    model = Teacher
    template_name = 'classroom/teacher_detail.html'
    context_object_name = 'teacher'

class TeacherUpdateView(UpdateView):
    model = Teacher
    fields = '__all__'
    template_name = 'classroom/teacher_form.html'
    success_url = reverse_lazy('classroom:teacher_list')

class TeacherDeleteView(DeleteView):
    model = Teacher
    template_name = 'classroom/teacher_confirm_delete.html'
    success_url = reverse_lazy('classroom:teacher_list')

school/classroom/templates/classroom/contact.html
<h1>Form View Template (contact.html)</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

school/classroom/templates/classroom/home.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to home.html</h1>
    <ul>
        <li>
            <a href="{% url 'classroom:thank_you' %}">Thank you page link</a>
        </li>
        <li>
            <a href="{% url 'classroom:contact' %}">Contact page link</a>
        </li>
        <li>
            <a href="{% url 'classroom:create_teacher' %}">Create New Teacher</a>
        </li>
        <li>
            <a href="{% url 'classroom:teacher_list' %}">List Teacher</a>
        </li>
    </ul>
</body>
</html>

school/classroom/templates/classroom/teacher_confirm_delete.html
<h1>Teacher Delete Confirmation</h1>
<form  method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{ teacher }}?</p>
    <input type="submit" value="Yes">
</form>

school/classroom/templates/classroom/teacher_detail.html
<h1>Teacher Detail View</h1>
{{teacher}}

school/classroom/templates/classroom/teacher_form.html
<h1>Teacher Form</h1>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

school/classroom/templates/classroom/teacher_list.html
<h1>List of Teachers (List Views)</h1>
<ul>
    {% for teacher in teachers %}
        <li>
            <a href="/classroom/teacher_detail/{{teacher.id}}">{{teacher.first_name}} {{teacher.last_name}}</a>
            <ul>
                <li><a href="/classroom/teacher_update/{{teacher.id}}">Update for {{teacher.first_name}}</a></li>
                <li><a href="/classroom/teacher_delete/{{teacher.id}}">Delete for {{teacher.first_name}}</a></li>
            </ul>
        </li>
    {% endfor %}
</ul>

school/classroom/templates/classroom/thank_you.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Thank you!</h1>
</body>
</html>