library/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("create_book", views.BookCreate.as_view(), name="create_book"),
    path("book/<int:pk>/", views.BookDetail.as_view(), name="book_detail"),
    path("my_view", views.my_view, name="my_view"),
    path("signup", views.SignUp.as_view(), name="signup"),
    path("profile", views.CheckedOutBooksByUserListView.as_view(), name="profile"),
]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls")),
    path("", RedirectView.as_view(url="/catalog/")),
    path("accounts/", include("django.contrib.auth.urls")),
]

library/catalog/models.py
from django.db import models
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
from django.contrib.auth.models import User # Required to assign User as a borrower

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=200, help_text='Enter the book\'s natural language (e.g. English, French, Japanese etc.)')

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', unique=True, max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"pk": self.pk})

class Author(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    date_of_birth = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author_detail', kwargs={'pk': self.pk})
    
    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

# Book instance model
import uuid

class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')

    class Meta:
        ordering = ['due_back']
    
    def __str__(self):
        return f'{self.id} ({self.book.title})'

library/catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Book, Author, BookInstance, Genre, Language
from django.views.generic import CreateView, DetailView, ListView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    
    context={
                'num_books': num_books, 
                'num_instances': num_instances,
                'num_instances_available': num_instances_available,
            }

    return render(request, 'catalog/index.html', context=context)

class BookCreate(LoginRequiredMixin,CreateView): # This will look for book_form.html and on success will redirect to book_detail.html
    model = Book
    fields = '__all__'

class BookDetail(DetailView):
    model = Book

@login_required
def my_view(request):
    return render(request,'catalog/my_view.html')

class SignUp(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'catalog/signup.html'

class CheckedOutBooksByUserListView(LoginRequiredMixin, ListView):
    # list all book instances but filter for the currently logged in user session
    model = BookInstance
    template_name = 'catalog/profile.html'
    paginate_by = 5 # pagination

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user)#.filter(status__exact='o').order_by('due_back')

library/catalog/templates/catalog/book_detail.html
<h1>Detail for book</h1>
{{book}}

library/catalog/templates/catalog/book_form.html
<h1>Create New Book</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
</form>

library/catalog/templates/catalog/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>HOMEPAGE</h1>
    <p>Total Books: {{num_books}}</p>
    <p>Num Available: {{num_instances_available}}</p>
    {% if user.is_authenticated %}
        <p>You are logged in</p>
        <p>Welcome {{user.get_username}}!</p>
        <a href="{% url 'logout' %}?next={{request.path}}">Logout</a>
    {% else %}
        <p>You are not logged in</p>
        <a href="{% url 'login' %}?next={{request.path}}">Login</a>
    {% endif %}
</body>
</html>

library/catalog/templates/catalog/my_view.html
<h1>Logged in users only</h1>

library/catalog/templates/catalog/profile.html
<h1>Welcome to your profile</h1>
<h2>Here are your booked checked out: </h2>
{% for book in bookinstance_list %}
    <p>{{book}}</p>
{% endfor %}

library/catalog/templates/catalog/signup.html
<h1>Register new user here</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="signup">
</form>