my_car_site/cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('list/', views.list, name='list'),
    path('add/', views.add, name='add'),
    path('delete/', views.delete, name='delete'),
]

my_car_site/my_car_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("cars/", include("cars.urls")),
]

my_car_site/cars/models.py
from django.db import models

# Create your models here.
class Car(models.Model):
    brand = models.CharField(max_length=30)
    year = models.IntegerField()

    def __str__(self):
        return f'Car is {self.brand} and year is {self.year}'

my_car_site/cars/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models

# Create your views here.
def list(request):
    all_cars = models.Car.objects.all()
    return render(request, 'cars/list.html', context={'all_cars': all_cars})

def add(request):
    if request.POST:
        brand = request.POST['brand']
        year = int(request.POST['year'])
        models.Car.objects.create(brand=brand, year=year)
        return redirect(reverse('cars:list'))
    return render(request, 'cars/add.html')

def delete(request):
    if request.POST:
        pk = request.POST['pk']
        try:
            models.Car.objects.filter(pk=pk).delete()
            return redirect(reverse('cars:list'))
        except:
            print('PK not found')
            return redirect(reverse('cars:list'))
    return render(request, 'cars/delete.html')

my_car_site/cars/templates/cars/add.html
{% extends 'base.html' %}

{% block content %}
<div class='container'>
    <h1>ADD.HTML</h1>
    <h2>Add a new car to the database
    <form action="" method="POST">
        {% csrf_token %}
        <div class='form-group'>
            <label for="brand">Brand:</label>
            <input class='form-control' type="text" name="brand" id="brand">
        </div>
        <div class='form-group'>
            <label for="year">Year:</label>
            <input class='form-control' type="text" name="year" id="year">
        </div>
        <input class='btn btn-primary' type='submit'>
    </form>
{% endblock content %}

my_car_site/cars/templates/cars/delete.html
{% extends 'base.html' %}

{% block content %}
<h1>DELETE.HTML</h1>
<form action="" method="post">
    {% csrf_token %}

    <div class="form-group">
        <label for="pk">PK Number: </label>
        <input class="form-control" type="text" name="pk" id="pk">
    </div>
    <input class="btn btn-primary" type="submit" value="Delete">
{% endblock content %}

my_car_site/cars/templates/cars/list.html
{% extends 'base.html' %}

{% block content %}
<div class='container'>
    <h1>LIST.HTML</h1>
    <ul>
        {% for item in all_cars %}
            <li>{{ item }}</li>
        {% endfor %}
{% endblock content %}

my_car_site/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    

</head>
<body>
    
    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg navbar-light">
        <div id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href={% url 'cars:list' %}>List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href={% url 'cars:add' %}>Add</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href={% url 'cars:delete' %}>Delete</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block content %}

    {% endblock %}



</body>
</html>